# Generated by Django 4.1.1 on 2022-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_sub_category_details",
            name="ram",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="product_sub_category_details",
            name="storage",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
