# Generated by Django 4.1.1 on 2022-09-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0002_product_sub_category_details_ram_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product_sub_category_details", name="ram",),
        migrations.RemoveField(
            model_name="product_sub_category_details", name="storage",
        ),
        migrations.AddField(
            model_name="product_sub_category_details",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
    ]
