# Generated by Django 4.1.1 on 2022-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0003_remove_product_sub_category_details_ram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_sub_category_details",
            name="model_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
