# Generated by Django 4.1.1 on 2022-09-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0004_product_sub_category_details_model_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_sub_category_details",
            old_name="name",
            new_name="product_mst",
        ),
    ]
