# Generated by Django 4.1.1 on 2022-09-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0005_rename_name_product_sub_category_details_product_mst"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_sub_category_details",
            name="porduct_image",
            field=models.ImageField(
                default="media/default.png", upload_to="media/product_images"
            ),
        ),
    ]
