# Generated by Django 4.1.1 on 2022-09-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0007_alter_product_sub_category_details_porduct_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_sub_category_details",
            old_name="porduct_image",
            new_name="product_image",
        ),
    ]
